# GENERATED by `kilau gen entities` from table "widgets". Do not edit;
# change the migration and regenerate.
module Entities
  class Widget
    TABLE = "widgets"
    COLUMNS = ["id", "name", "note", "created_at", "updated_at"]
    SELECT_SQL = "SELECT id, name, note, created_at, updated_at FROM widgets"
    INSERT_SQL = "INSERT INTO widgets (name, note, created_at, updated_at) VALUES (?, ?, ?, ?)"
    UPDATE_SQL = "UPDATE widgets SET name = ?, note = ?, created_at = ?, updated_at = ? WHERE id = ?"
    DELETE_SQL = "DELETE FROM widgets WHERE id = ?"

    attr_accessor :id, :name, :note, :created_at, :updated_at

    def self.select_sql = SELECT_SQL

    def self.from_row(row)
      entity = new
      entity.id = row.int(0)
      entity.name = row.text(1)
      entity.note = row.text_or_nil(2)
      entity.created_at = row.int(3)
      entity.updated_at = row.int(4)
      entity
    end

    def insert_sql = INSERT_SQL
    def update_sql = UPDATE_SQL
    def delete_sql = DELETE_SQL
    def insert_binds = [@name, @note, @created_at, @updated_at]
    def update_binds = [@name, @note, @created_at, @updated_at, @id]

    def touch(now)
      @created_at = now if @created_at.nil?
      @updated_at = now
    end
  end
end
