# GENERATED by `kilau gen routes` from src/. Do not edit; change the
# routes and regenerate. Each handler body is copied from its route
# block into a class method of the class that declared it, so self
# is that class, and the dispatcher below calls it directly.

class NotesApp
  # src/app.rb:5: GET /
  def self.kilau_route_2(app_context, request)
    Kilau::Format.render("home")
  end
end

class NotesController
  # src/controllers/notes.rb:4: GET /notes
  def self.kilau_route_3(c, r)
    list(c, r)
  end
  # src/controllers/notes.rb:5: GET /notes/:id
  def self.kilau_route_4(c, r)
    show(r.path_params.fetch("id"))
  end
  # src/controllers/notes.rb:6: GET /notes/:id/tags/:tag
  def self.kilau_route_5(app_context, request)
    Kilau::Format.render("#{request.path_params["id"]}/#{request.path_params["tag"]} {}")
  end
  # src/controllers/notes.rb:7: DELETE /notes/:id
  def self.kilau_route_6(app_context, request)
    Kilau::Format.empty(204)
  end
end

module KilauRoutes
  # What the app's route table holds, in order; a test compares the two.
  TABLE = ["GET /_ping", "GET /_health", "GET /", "GET /notes", "GET /notes/:id", "GET /notes/:id/tags/:tag", "DELETE /notes/:id"]

  class Dispatcher
    def initialize(app_context)
      @app_context = app_context
    end

    def call(request)
      Kilau::Dispatcher.apply_override(request)
      app_context = @app_context
      parts = request.path.split("/")
      parts.shift
      case request.request_method
      when "GET"
        if parts.size == 1 && parts[0] == "_ping"
          request.path_params = {}
          return Kilau::AppRoutes.ping(app_context, request)
        end
        if parts.size == 1 && parts[0] == "_health"
          request.path_params = {}
          return Kilau::AppRoutes.health(app_context, request)
        end
        if parts.empty?
          request.path_params = {}
          return NotesApp.kilau_route_2(app_context, request)
        end
        if parts.size == 1 && parts[0] == "notes"
          request.path_params = {}
          return NotesController.kilau_route_3(app_context, request)
        end
        if parts.size == 2 && parts[0] == "notes" && !parts[1].empty?
          request.path_params = { "id" => parts[1] }
          return NotesController.kilau_route_4(app_context, request)
        end
        if parts.size == 4 && parts[0] == "notes" && !parts[1].empty? && parts[2] == "tags" && !parts[3].empty?
          request.path_params = { "id" => parts[1], "tag" => parts[3] }
          return NotesController.kilau_route_5(app_context, request)
        end
      when "DELETE"
        if parts.size == 2 && parts[0] == "notes" && !parts[1].empty?
          request.path_params = { "id" => parts[1] }
          return NotesController.kilau_route_6(app_context, request)
        end
      end
      Kilau::Dispatcher.error_response(404, "no route for #{request.request_method} #{request.path}")
    rescue Kilau::Error => e
      Kilau::Dispatcher.error_response(e.status, e.message)
    rescue StandardError => e
      $stderr.puts "kilau: #{e.class}: #{e.message}"
      Kilau::Dispatcher.error_response(500, "internal server error")
    end
  end
end

# The app, served by the dispatcher above: bin/<app>_routes.rb runs
# Kilau::CLI.run(RoutedNotesApp.new, ...).
class RoutedNotesApp < NotesApp
  def dispatcher(app_context) = KilauRoutes::Dispatcher.new(app_context)
end
