# GENERATED by `kilau gen templates` from assets/views. Do not edit;
# change the template and regenerate.
module Templates
  # assets/views/items/_item.html
  def self.items__item(item)
    buf = +""
    # assets/views/items/_item.html:3
    buf << "<li>"
    # assets/views/items/_item.html:3
    buf << Kilau::Html.escape((item).to_s)
    # assets/views/items/_item.html:3
    buf << "</li>\n"
    buf
  end

  # assets/views/items/list.html
  def self.items_list(items, note)
    block_title = +""
    # assets/views/items/list.html:3
    block_title << "Items"
    block_content = +""
    # assets/views/items/list.html:5
    block_content << "<ul>\n"
    (items).each do |item|
      # assets/views/items/list.html:7
      block_content << Templates.items__item(item)
    end
    # assets/views/items/list.html:9
    block_content << "</ul>\n"
    if note.empty?
      # assets/views/items/list.html:11
      block_content << "<p>none</p>\n"
    elsif note == "x" || note.start_with?("<")
      # assets/views/items/list.html:13
      block_content << "<p>"
      # assets/views/items/list.html:13
      block_content << Kilau::Html.escape((note).to_s)
      # assets/views/items/list.html:13
      block_content << " | "
      # assets/views/items/list.html:13
      block_content << (note).to_s
      # assets/views/items/list.html:13
      block_content << "</p>\n"
    else
      # assets/views/items/list.html:15
      block_content << "<p class=\"n\">\#{raw} "
      # assets/views/items/list.html:15
      block_content << Kilau::Html.escape((note.size).to_s)
      # assets/views/items/list.html:15
      block_content << "</p>\n"
    end
    Templates.layout(block_title, block_content)
  end

  # assets/views/layout.html
  def self.layout(block_title, block_content)
    buf = +""
    # assets/views/layout.html:2
    buf << "<title>"
    if block_title.nil?
      # assets/views/layout.html:2
      buf << "Kilau"
    else
      buf << block_title
    end
    # assets/views/layout.html:2
    buf << "</title>\n<main>\n"
    if block_content.nil?
    else
      buf << block_content
    end
    # assets/views/layout.html:4
    buf << "\n</main>\n"
    buf
  end

  # assets/views/pairs.html
  def self.pairs(errors)
    buf = +""
    (errors).each do |field, message|
      # assets/views/pairs.html:2
      buf << Kilau::Html.escape((field).to_s)
      # assets/views/pairs.html:2
      buf << ": "
      # assets/views/pairs.html:2
      buf << Kilau::Html.escape((message).to_s)
      # assets/views/pairs.html:2
      buf << "\n"
    end
    buf
  end

  # assets/views/plain.html
  def self.plain
    block_content = +""
    # assets/views/plain.html:3
    block_content << "<p>plain</p>"
    Templates.layout(nil, block_content)
  end
end
