module KilauTool
  # Writes Entities::<Class> source from a table's PRAGMA table_info, in
  # the shape Kilau::Model expects: SQL constants, binds, from_row, touch.
  module EntitiesGen
    class Column
      attr_reader :name, :sql_type, :not_null, :primary_key

      def initialize(name, sql_type, not_null, primary_key)
        @name = name
        @sql_type = sql_type
        @not_null = not_null
        @primary_key = primary_key
      end

      # The Kilau::DB::Row reader for this column. A NOT NULL column (and
      # the primary key) reads as its plain type, so it stays narrow.
      def reader
        base = case @sql_type
               when "INTEGER" then "int"
               when "TEXT" then "text"
               when "REAL" then "float"
               else raise ArgumentError, "unsupported column type #{@sql_type} for #{@name}"
               end
        @not_null || @primary_key ? base : "#{base}_or_nil"
      end
    end

    def self.class_name(table)
      singular = if table.end_with?("ies")
                   table[0, table.size - 3] + "y"
                 elsif table.end_with?("s")
                   table[0, table.size - 1]
                 else
                   table
                 end
      singular.split("_").map { |part| part.capitalize }.join
    end

    def self.render(table, columns)
      primary = columns.find { |c| c.primary_key }
      if primary.nil? || primary.name != "id"
        raise ArgumentError, "table #{table}: Kilau::Model needs an INTEGER primary key named id"
      end
      names = columns.map { |c| c.name }
      writable = columns.reject { |c| c.primary_key }.map { |c| c.name }
      placeholders = writable.map { |n| "?" }.join(", ")
      assignments = writable.map { |n| "#{n} = ?" }.join(", ")
      quoted = names.map { |n| "\"#{n}\"" }.join(", ")
      symbols = names.map { |n| ":#{n}" }.join(", ")
      insert_ivars = writable.map { |n| "@#{n}" }.join(", ")
      update_ivars = (writable + ["id"]).map { |n| "@#{n}" }.join(", ")

      lines = []
      lines << "# GENERATED by `kilau gen entities` from table \"#{table}\". Do not edit;"
      lines << "# change the migration and regenerate."
      lines << "module Entities"
      lines << "  class #{class_name(table)}"
      lines << "    TABLE = \"#{table}\""
      lines << "    COLUMNS = [#{quoted}]"
      lines << "    SELECT_SQL = \"SELECT #{names.join(", ")} FROM #{table}\""
      lines << "    INSERT_SQL = \"INSERT INTO #{table} (#{writable.join(", ")}) VALUES (#{placeholders})\""
      lines << "    UPDATE_SQL = \"UPDATE #{table} SET #{assignments} WHERE id = ?\""
      lines << "    DELETE_SQL = \"DELETE FROM #{table} WHERE id = ?\""
      lines << ""
      lines << "    attr_accessor #{symbols}"
      lines << ""
      lines << "    def self.select_sql = SELECT_SQL"
      lines << ""
      lines << "    def self.from_row(row)"
      lines << "      entity = new"
      columns.each_with_index { |c, i| lines << "      entity.#{c.name} = row.#{c.reader}(#{i})" }
      lines << "      entity"
      lines << "    end"
      lines << ""
      lines << "    def insert_sql = INSERT_SQL"
      lines << "    def update_sql = UPDATE_SQL"
      lines << "    def delete_sql = DELETE_SQL"
      lines << "    def insert_binds = [#{insert_ivars}]"
      lines << "    def update_binds = [#{update_ivars}]"
      lines << ""
      lines << "    def touch(now)"
      lines << "      @created_at = now if @created_at.nil?" if names.include?("created_at")
      lines << "      @updated_at = now" if names.include?("updated_at")
      lines << "    end"
      lines << "  end"
      lines << "end"
      lines.join("\n") + "\n"
    end

    TABLES_SQL = "SELECT name FROM sqlite_master WHERE type = 'table' " \
                 "AND name NOT LIKE 'sqlite_%' AND name != 'schema_migrations' ORDER BY name"

    # Reads every user table of the SQLite file at db_path and writes
    # <out_dir>/<table>.rb. Returns the paths written, by table name.
    def self.generate(db_path, out_dir)
      raise ArgumentError, "no database at #{db_path}" unless File.exist?(db_path)
      raise ArgumentError, "no directory at #{out_dir}" unless File.directory?(out_dir)
      conn = Kilau::DB::Connection.open(db_path)
      written = []
      begin
        tables = []
        conn.query(TABLES_SQL, []) { |row| tables << row.text(0) }
        tables.each do |table|
          columns = []
          conn.query("PRAGMA table_info(#{table})", []) do |row|
            columns << Column.new(row.text(1), row.text(2).upcase, row.int(3) == 1, row.int(5) > 0)
          end
          path = "#{out_dir}/#{table}.rb"
          File.write(path, render(table, columns))
          written << path
        end
      ensure
        conn.close
      end
      written
    end
  end
end
