require_relative "template"

module KilauTool
  # Compiles assets/views/**/*.html into one Ruby file of Templates.*
  # methods (spec §4). Nothing is interpreted at runtime: each template is
  # a method that appends to a String buffer, so its values stay as typed
  # as the arguments the view functions pass in.
  module TemplateCompile
    ROOT = "assets/views"
    FILTERS = ["safe"]

    # Reads <app_dir>/assets/views, writes <app_dir>/build/gen/templates.rb,
    # returns its path. Nothing is written when any template fails.
    def self.generate(app_dir)
      root = "#{app_dir}/#{ROOT}"
      raise ArgumentError, "no template directory at #{root}" unless File.directory?(root)
      files = Dir.glob("#{root}/**/*.html").sort
      raise ArgumentError, "no templates under #{root}" if files.empty?
      templates = files.map { |file| Template.parse(file[root.size + 1, file.size - root.size - 1], File.read(file)) }
      source = render(templates)
      build = "#{app_dir}/build"
      gen = "#{build}/gen"
      Dir.mkdir(build) unless File.directory?(build)
      Dir.mkdir(gen) unless File.directory?(gen)
      path = "#{gen}/templates.rb"
      File.write(path, source)
      path
    end

    # templates: sorted by path. Returns the source of module Templates.
    def self.render(templates)
      index = {}
      owners = {}
      templates.each do |template|
        other = owners[template.method_name]
        unless other.nil?
          raise ArgumentError, "#{other} and #{template.path} both compile to Templates.#{template.method_name}"
        end
        owners[template.method_name] = template.path
        index[template.path] = template
      end
      check_cycles(templates, index)
      out = []
      out << "# GENERATED by `kilau gen templates` from #{ROOT}. Do not edit;"
      out << "# change the template and regenerate."
      out << "module Templates"
      templates.each_with_index do |template, i|
        out << "" if i > 0
        Unit.new(template, index).emit(out)
      end
      out << "end"
      out.join("\n") + "\n"
    end

    def self.keyword(tag)
      space = tag.index(" ")
      space.nil? ? tag : tag[0, space]
    end

    def self.rest(tag)
      space = tag.index(" ")
      space.nil? ? "" : tag[space + 1, tag.size - space - 1].strip
    end

    # The path inside {% include "x.html" %} / {% extends "x.html" %}.
    def self.quoted(text, path, line)
      unless text.size >= 2 && text.start_with?("\"") && text.end_with?("\"")
        raise ArgumentError, "#{path}:#{line}: expected a quoted template path, got #{text}"
      end
      text[1, text.size - 2]
    end

    # "" when the template does not extend. extends must be its first tag,
    # with only blank text before it.
    def self.extends_target(template)
      tokens = template.tokens
      i = 0
      i += 1 while i < tokens.size && tokens[i].kind == "text" && tokens[i].text.strip.empty?
      first = i < tokens.size && tokens[i].kind == "tag" && keyword(tokens[i].text) == "extends"
      target = first ? quoted(rest(tokens[i].text), template.path, tokens[i].line) : ""
      tokens.each_with_index do |token, j|
        if token.kind == "tag" && keyword(token.text) == "extends" && !(first && j == i)
          raise ArgumentError, "#{template.path}:#{token.line}: {% extends %} must be the first tag, and only once"
        end
      end
      target
    end

    def self.blocks_of(template)
      names = []
      template.tokens.each do |token|
        names << rest(token.text) if token.kind == "tag" && keyword(token.text) == "block"
      end
      names
    end

    def self.references(template)
      targets = []
      template.tokens.each do |token|
        word = token.kind == "tag" ? keyword(token.text) : ""
        targets << quoted(rest(token.text), template.path, token.line) if word == "include" || word == "extends"
      end
      targets
    end

    def self.check_cycles(templates, index)
      done = {}
      templates.each { |template| visit(template, index, [], done) }
    end

    def self.visit(template, index, trail, done)
      return if done.key?(template.path)
      at = trail.index(template.path)
      unless at.nil?
        raise ArgumentError, "template cycle: #{(trail[at, trail.size - at] + [template.path]).join(" -> ")}"
      end
      trail << template.path
      references(template).each do |target|
        other = index[target]
        visit(other, index, trail, done) unless other.nil?
      end
      trail.pop
      done[template.path] = true
    end

    # "x | safe" -> "safe"; "" when the expression has no filter. A || is
    # Ruby's or, not a filter.
    def self.filter_of(expr)
      bar = expr.rindex("|")
      return "" if bar.nil? || bar == 0 || expr[bar - 1] == "|"
      name = expr[bar + 1, expr.size - bar - 1].strip
      Template.identifier?(name) ? name : ""
    end

    def self.code_of(expr)
      return expr if filter_of(expr).empty?
      expr[0, expr.rindex("|")].strip
    end

    # The local names an expression reads: identifiers that start it or
    # follow an operator, not method names after a dot, constants, hash
    # keys, keywords, or anything inside a string literal.
    def self.free_identifiers(expr)
      found = []
      prev = ""
      i = 0
      while i < expr.size
        c = expr[i]
        if c == "\"" || c == "'"
          i = after_string(expr, i)
          prev = c
        elsif Template.word_char?(c)
          j = i
          j += 1 while j < expr.size && Template.word_char?(expr[j])
          j += 1 if j < expr.size && (expr[j] == "?" || expr[j] == "!")
          name = expr[i, j - i]
          hash_key = j < expr.size && expr[j] == ":" && (j + 1 == expr.size || expr[j + 1] != ":")
          local = Template.lower_start?(c) && prev != "." && prev != ":" && prev != "@" && prev != "$"
          if local && !hash_key && !Template::KEYWORDS.include?(name) && !found.include?(name)
            found << name
          end
          prev = "a"
          i = j
        else
          prev = c unless c == " "
          i += 1
        end
      end
      found
    end

    def self.after_string(expr, start)
      quote = expr[start]
      i = start + 1
      while i < expr.size
        return i + 1 if expr[i] == quote
        i += expr[i] == "\\" ? 2 : 1
      end
      i
    end

    # Compiles one template into one def self.<method_name>.
    class Unit
      def initialize(template, index)
        @template = template
        @index = index
        @body = []
        @indent = 4
        @buf = "buf"
        @scope = template.args.dup
        @open = []
        @open_lines = []
        @scope_marks = []
        @block_name = ""
        @layout = nil
        @filled = []
      end

      def emit(out)
        target = TemplateCompile.extends_target(@template)
        if target.empty?
          params = @template.args + TemplateCompile.blocks_of(@template).map { |name| "block_#{name}" }
          @template.tokens.each { |token| step(token) }
          finish
          out << "  # #{ROOT}/#{@template.path}"
          out << (params.empty? ? "  def self.#{@template.method_name}" : "  def self.#{@template.method_name}(#{params.join(", ")})")
          out << "    buf = +\"\""
          @body.each { |line| out << line }
          out << "    buf"
        else
          @layout = lookup(target, first_line)
          if TemplateCompile.extends_target(@layout) != ""
            raise ArgumentError, "#{@template.path}: #{target} extends another template; layouts nest one level only"
          end
          @template.tokens.each { |token| child_step(token) }
          finish
          out << "  # #{ROOT}/#{@template.path}"
          out << (@template.args.empty? ? "  def self.#{@template.method_name}" : "  def self.#{@template.method_name}(#{@template.args.join(", ")})")
          @body.each { |line| out << line }
          out << "    Templates.#{@layout.method_name}(#{layout_call_args.join(", ")})"
        end
        out << "  end"
      end

      private

      def first_line
        @template.tokens.empty? ? 2 : @template.tokens[0].line
      end

      def lookup(target, line)
        template = @index[target]
        raise ArgumentError, "#{@template.path}:#{line}: no template #{target} under #{ROOT}" if template.nil?
        template
      end

      def error_at(line, message)
        raise ArgumentError, "#{@template.path}:#{line}: #{message}"
      end

      def put(code)
        @body << (" " * @indent) + code
      end

      def mark(line)
        put("# #{ROOT}/#{@template.path}:#{line}")
      end

      # Outside every block of a template that extends, only blank text
      # and block tags may appear: nothing else would reach the page.
      def child_step(token)
        if token.kind == "tag" && TemplateCompile.keyword(token.text) == "extends"
          nil
        elsif !@open.empty?
          step(token)
        elsif token.kind == "text"
          error_at(token.line, "text outside {% block %} in a template that extends") unless token.text.strip.empty?
        elsif token.kind == "tag" && TemplateCompile.keyword(token.text) == "block"
          open_child_block(TemplateCompile.rest(token.text), token.line)
        else
          error_at(token.line, "only {% block %} may appear at the top of a template that extends")
        end
      end

      def step(token)
        case token.kind
        when "text"
          mark(token.line)
          put("#{@buf} << #{token.text.inspect}")
        when "expr"
          output(token)
        else
          tag(token)
        end
      end

      def output(token)
        filter = TemplateCompile.filter_of(token.text)
        error_at(token.line, "unknown filter #{filter}; the only filter is safe") unless filter.empty? || FILTERS.include?(filter)
        code = TemplateCompile.code_of(token.text)
        check_expr(code, token.line)
        mark(token.line)
        if filter == "safe"
          put("#{@buf} << (#{code}).to_s")
        else
          put("#{@buf} << Kilau::Html.escape((#{code}).to_s)")
        end
      end

      def check_expr(code, line)
        error_at(line, "empty expression") if code.empty?
        TemplateCompile.free_identifiers(code).each do |name|
          error_at(line, "#{name} is not an argument or loop variable here (args: #{@scope.join(", ")})") unless @scope.include?(name)
        end
      end

      def tag(token)
        word = TemplateCompile.keyword(token.text)
        rest = TemplateCompile.rest(token.text)
        line = token.line
        case word
        when "if"
          check_expr(rest, line)
          put("if #{rest}")
          push_open("if", line)
        when "elif"
          error_at(line, "{% elif %} outside {% if %}") unless top == "if"
          check_expr(rest, line)
          put_outer("elsif #{rest}")
        when "else"
          error_at(line, "{% else %} outside {% if %}") unless top == "if"
          put_outer("else")
          @open[@open.size - 1] = "else"
        when "endif"
          error_at(line, "{% endif %} without {% if %}") unless top == "if" || top == "else"
          pop_open
        when "for"
          open_for(rest, line)
        when "endfor"
          error_at(line, "{% endfor %} without {% for %}") unless top == "for"
          pop_open
          @scope = @scope[0, @scope_marks.pop]
        when "include"
          include_template(rest, line)
        when "block"
          open_layout_block(rest, line)
        when "endblock"
          error_at(line, "{% endblock %} without {% block %}") unless top == "block"
          close_block
        when "extends"
          error_at(line, "{% extends %} must be the first tag")
        else
          error_at(line, "unknown tag {% #{word} %}")
        end
      end

      def top
        @open.empty? ? "" : @open.last
      end

      def push_open(kind, line)
        @open << kind
        @open_lines << line
        @indent += 2
      end

      def pop_open
        @open.pop
        @open_lines.pop
        @indent -= 2
        put("end")
      end

      def put_outer(code)
        @indent -= 2
        put(code)
        @indent += 2
      end

      # for x in expr / for k, v in expr
      def open_for(rest, line)
        at = rest.index(" in ")
        error_at(line, "expected {% for x in expr %}") if at.nil?
        names = rest[0, at].split(",").map { |name| name.strip }
        expr = rest[at + 4, rest.size - at - 4].strip
        error_at(line, "{% for %} takes one or two loop variables") if names.empty? || names.size > 2
        check_expr(expr, line)
        names.each do |name|
          Template.check_name(name, @template.path, line)
          error_at(line, "loop variable #{name} shadows a variable already in scope") if @scope.include?(name)
        end
        put("(#{expr}).each do |#{names.join(", ")}|")
        push_open("for", line)
        @scope_marks << @scope.size
        names.each { |name| @scope << name }
      end

      # The included template's args are passed by name from this scope.
      def include_template(rest, line)
        target = lookup(TemplateCompile.quoted(rest, @template.path, line), line)
        target.args.each do |name|
          error_at(line, "#{target.path} needs #{name}, which is not in scope here") unless @scope.include?(name)
        end
        mark(line)
        put("#{@buf} << Templates.#{target.method_name}(#{target.args.join(", ")})")
      end

      # In a layout, a block renders what the child filled in, else its
      # own content.
      def open_layout_block(name, line)
        error_at(line, "{% block %} must not be nested in another tag") unless @open.empty?
        error_at(line, "#{name.inspect} is not a valid block name") unless Template.identifier?(name)
        error_at(line, "block #{name} is declared twice") if @filled.include?(name)
        @filled << name
        put("if block_#{name}.nil?")
        push_open("block", line)
        @block_name = name
      end

      def open_child_block(name, line)
        unless TemplateCompile.blocks_of(@layout).include?(name)
          error_at(line, "#{@layout.path} has no {% block #{name} %}")
        end
        error_at(line, "block #{name} is filled twice") if @filled.include?(name)
        @filled << name
        put("block_#{name} = +\"\"")
        @buf = "block_#{name}"
        @block_name = name
        @open << "block"
        @open_lines << line
      end

      def close_block
        if @layout.nil?
          put_outer("else")
          put("buf << block_#{@block_name}")
          pop_open
        else
          @open.pop
          @open_lines.pop
          @buf = "buf"
        end
      end

      def finish
        error_at(@open_lines.last, "{% #{@open.last == "else" ? "if" : @open.last} %} is never closed") unless @open.empty?
      end

      def layout_call_args
        @layout.args.each do |name|
          unless @template.args.include?(name)
            raise ArgumentError, "#{@template.path}: #{@layout.path} needs #{name}, which is not an argument here"
          end
        end
        @layout.args + TemplateCompile.blocks_of(@layout).map { |name| @filled.include?(name) ? "block_#{name}" : "nil" }
      end
    end
  end
end
